import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import { router } from "./router";
import { setupRouteAccess } from "./access";
import "./styles/tokens.css";
import "./styles/ui.css";
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
setupRouteAccess(router);
app.use(router);
app.mount("#app");
